### ISSUE TITLE
missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [septetsystems/moodle-plagiarism_plagium#1]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. Your plugin stores user data and exports data to an external API which will need to be included in the privaci api classes.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API 

Please note, privacy api compliance is a blocker for moodle.org plugins db approval for plugins that integrate with an external API like this one.

**Comment by septetaccount** [comment]
This issue has been resolved
