### ISSUE TITLE
Please don't call curl_init directly

### ISSUE THREAD

**Issue by danmarsden** [septetsystems/moodle-plagiarism_plagium#3]
https://github.com/septetsystems/moodle-plagiarism_plagium/blob/main/classes/plagium_api.php#L44

Please don't initate curl_init() directly but use Moodle's own "curl" class which is a wrapper on PHP's curl functions.

Do a search for curl() in core Moodle code to see examples of it's use.

**Comment by septetaccount** [comment]
This is resolved.
