### ISSUE TITLE
don't query config_plugins table using db queries

### ISSUE THREAD

**Issue by danmarsden** [septetsystems/moodle-plagiarism_plagium#4]
https://github.com/septetsystems/moodle-plagiarism_plagium/blob/main/classes/plagium_upload.php#L32

the config is cached - use get_config() api functions to get these values.

**Comment by danmarsden** [comment]
more examples:
https://github.com/septetsystems/moodle-plagiarism_plagium/blob/fb1b1a1edfc731f1b4cb068c9383753d821be498/classes/plagium_connect.php#L269

**Comment by danmarsden** [comment]
and this stuff should be using set_config() api:
https://github.com/septetsystems/moodle-plagiarism_plagium/blob/main/classes/plagium_connect.php#L107

**Comment by septetaccount** [comment]
this resolved
