### ISSUE TITLE
ajax.php appears to perform no permission checks

### ISSUE THREAD

**Issue by danmarsden** [septetsystems/moodle-plagiarism_plagium#5]
The ajax.php performs a require_login() at the top but does not check 
"Does this user have access to view the course associated with this record"
"Does this user have the permissions to perform the action being requested"

This means that any user who has a login in the site appears to be able to access plagiarism reporting data for all files submitted to the plagiarism service (privacy/security issue.)

**Comment by septetaccount** [comment]
Resoved in [ajax.php line #18 ](https://github.com/septetsystems/moodle-plagiarism_plagium/blob/77737076abf10c3b7ae9152e01a3af8825935fd0/ajax.php#L18)
